'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/versions.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Versions() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Versions"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/Authentication.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Authentication() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/imaging.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Imaging() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Imaging"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/People.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_People() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_People"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/SharepointEmailWS.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SharepointEmailWS() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SharepointEmailWS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/dspsts.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_StsAdapter() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_StsAdapter"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/dws.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Dws() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Dws"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/sites.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Sites() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Sites"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/alerts.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Alerts() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Alerts"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/SiteData.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SiteData() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SiteData"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/views.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Views() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Views"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/spsearch.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_QueryService() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_QueryService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/UserGroup.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_UserGroup() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_UserGroup"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/webs.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Webs() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Webs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/permissions.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Permissions() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Permissions"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/meetings.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Meetings() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Meetings"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/forms.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Forms() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Forms"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/copy.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_Copy() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_Copy"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/_vti_bin/WebPartPages.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_WebPartPagesWebService() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_WebPartPagesWebService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/views.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Views() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Views"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/sites.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Sites() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Sites"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/dspsts.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_StsAdapter() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_StsAdapter"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/WebPartPages.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_WebPartPagesWebService() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_WebPartPagesWebService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/UserGroup.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_UserGroup() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_UserGroup"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/spsearch.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_QueryService() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_QueryService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/permissions.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Permissions() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Permissions"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/meetings.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Meetings() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Meetings"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/dws.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Dws() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Dws"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/alerts.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Alerts() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Alerts"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/copy.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Copy() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Copy"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/SiteData.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_SiteData() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_SiteData"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/SharepointEmailWS.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_SharepointEmailWS() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_SharepointEmailWS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/imaging.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Imaging() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Imaging"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/forms.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Forms() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Forms"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/Authentication.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Authentication() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/versions.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Versions() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Versions"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/People.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_People() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_People"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/webs.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Webs() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Webs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://spbprd4/SD/_vti_bin/lists.asmx")>  _
        Public ReadOnly Property PurchaserWorkplace_spbprd4_SD_Lists() As String
            Get
                Return CType(Me("PurchaserWorkplace_spbprd4_SD_Lists"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\SPBPRD4\Store\PUBLIC\Logistics\Счета\")>  _
        Public ReadOnly Property BillPath() As String
            Get
                Return CType(Me("BillPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PUBLIC\Logistics\Счета\")>  _
        Public ReadOnly Property BillCommonPath() As String
            Get
                Return CType(Me("BillCommonPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LibreOffice")>  _
        Public ReadOnly Property UseOffice() As String
            Get
                Return CType(Me("UseOffice"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PurchaserWorkplace.My.MySettings
            Get
                Return Global.PurchaserWorkplace.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
