Public Class ItemSelectList

    Public MySrcWin As String                         'окно, из которого вызвано

    Private Sub Button5_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button5.Click
        '/////////////////////////////////////////////////////////////////////////////////////
        '//
        '// Выход без выбора запаса
        '// 
        '/////////////////////////////////////////////////////////////////////////////////////

        Me.Close()
    End Sub

    Private Sub Button4_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button4.Click
        '/////////////////////////////////////////////////////////////////////////////////////
        '//
        '// Выход с выбором запаса
        '// 
        '/////////////////////////////////////////////////////////////////////////////////////

        ItemSelect()
    End Sub

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        '////////////////////////////////////////////////////////////////////////////////////////
        '//Открытие окна с детальной информацией по складам
        '//
        '////////////////////////////////////////////////////////////////////////////////////////

        MyShowWHDetails = New ShowWHDetails
        MyShowWHDetails.MyItem = Trim(Me.DataGridView1.SelectedRows.Item(0).Cells(1).Value.ToString())
        MyShowWHDetails.ShowDialog()
    End Sub

    Public Sub ItemSelect()
        '/////////////////////////////////////////////////////////////////////////////////////
        '//
        '// Выход с выбором запаса
        '// 
        '/////////////////////////////////////////////////////////////////////////////////////

        If MyItemSelectList.MySrcWin = "OrderLines" Then
            For i As Integer = 0 To MyOrderLines.DataGridView1.Rows.Count - 1
                If Trim(MyOrderLines.DataGridView1.Item(1, i).Value.ToString) = Trim(Me.DataGridView1.SelectedRows.Item(0).Cells(1).Value.ToString()) Then
                    MyOrderLines.DataGridView1.CurrentCell = MyOrderLines.DataGridView1.Item(1, i)
                    Me.Close()
                    Exit Sub
                End If
            Next
        ElseIf MyItemSelectList.MySrcWin = "ItemSelect" Then
            For i As Integer = 0 To MyItemSelect.DataGridView1.Rows.Count - 1
                If Trim(MyItemSelect.DataGridView1.Item(1, i).Value.ToString) = Trim(Me.DataGridView1.SelectedRows.Item(0).Cells(1).Value.ToString()) Then
                    MyItemSelect.DataGridView1.CurrentCell = MyItemSelect.DataGridView1.Item(1, i)
                    Me.Close()
                    Exit Sub
                End If
            Next
        End If
        Me.Close()
    End Sub

    Private Sub ItemSelectList_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        '/////////////////////////////////////////////////////////////////////////////////////
        '//
        '// При запуске загружаем список запасов
        '// 
        '/////////////////////////////////////////////////////////////////////////////////////
        Dim MySQLStr As String                        'рабочая строка
        Dim MyAdapter As SqlClient.SqlDataAdapter     '
        Dim MyDs As New DataSet                       '

        If MyItemSelectList.MySrcWin = "OrderLines" Then
            If Trim(MyOrderLines.TextBox2.Text) = "" Then
                '----В первое окно условие не введено - считаем, что во второе введено
                'MySQLStr = "SELECT tbl_WEB_Pictures.PictureSmall, SC010300.SC01001 AS ID, "
                MySQLStr = "SELECT NULL, SC010300.SC01001 AS ID, "
                MySQLStr = MySQLStr & "SC010300.SC01002 + ' ' + SC010300.SC01003 AS Name, "
                MySQLStr = MySQLStr & "Round(ISNULL(t2.SC39005, 0) / " & Replace(CStr(Declarations.CurrencyValue), ",", ".") & ",2) AS Price, "
                MySQLStr = MySQLStr & "SC010300.SC01060 AS SuppID, "
                MySQLStr = MySQLStr & "View_1.txt AS UnitName, "
                MySQLStr = MySQLStr & "SC010300.SC01042 AS TotalQty, "
                MySQLStr = MySQLStr & "ISNULL(t1.WhQty, 0) AS WhQty, "
                MySQLStr = MySQLStr & "ISNULL(t1.WhAvl, 0) AS WhAvl, "
                MySQLStr = MySQLStr & "SC010300.SC01058 AS SuppCode, "
                MySQLStr = MySQLStr & "ISNULL(PL010300.PL01002, N'') + ' ' + ISNULL(PL010300.PL01003, N'') AS SuppName, "
                '---поставщик "неликвидов"
                MySQLStr = MySQLStr & "CASE WHEN Ltrim(Rtrim(SC010300.SC01058)) = 'FIN001_U' THEN '+' ELSE '' END AS Dead, "
                MySQLStr = MySQLStr & "LTRIM(RTRIM(tbl_ItemCard0300.ManufacturerItemCode)) AS ManufacturerItemCode "
                MySQLStr = MySQLStr & "FROM SC010300 WITH (NOLOCK) INNER JOIN "
                MySQLStr = MySQLStr & "(SELECT 0 AS Expr1, SC09002 AS txt "
                MySQLStr = MySQLStr & "FROM SC090300 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 1 AS Expr1, SC09003 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_40 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 2 AS Expr1, SC09004 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_39 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 3 AS Expr1, SC09005 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_38 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 4 AS Expr1, SC09006 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_37 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 5 AS Expr1, SC09007 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_36 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 6 AS Expr1, SC09008 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_35 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 7 AS Expr1, SC09009 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_34 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 8 AS Expr1, SC09010 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_33 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 9 AS Expr1, SC09011 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_32 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 10 AS Expr1, SC09012 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_31 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 11 AS Expr1, SC09013 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_30 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 12 AS Expr1, SC09014 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_29 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 13 AS Expr1, SC09015 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_28 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 14 AS Expr1, SC09016 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_27 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 15 AS Expr1, SC09017 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_26 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 16 AS Expr1, SC09018 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_25 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 17 AS Expr1, SC09019 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_24 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 18 AS Expr1, SC09020 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_23 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 19 AS Expr1, SC09021 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_22 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 20 AS Expr1, SC09022 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_21 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 21 AS Expr1, SC09023 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_20 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 22 AS Expr1, SC09024 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_19 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 23 AS Expr1, SC09025 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_18 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 24 AS Expr1, SC09026 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_17 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 25 AS Expr1, SC09027 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_16 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 26 AS Expr1, SC09028 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_15 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 27 AS Expr1, SC09029 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_14 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 28 AS Expr1, SC09030 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_13 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 29 AS Expr1, SC09031 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_12 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 30 AS Expr1, SC09032 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_11 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 31 AS Expr1, SC09033 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_10 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 32 AS Expr1, SC09034 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_9 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 33 AS Expr1, SC09035 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_8 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 34 AS Expr1, SC09036 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_7 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 35 AS Expr1, SC09037 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_6 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 36 AS Expr1, SC09038 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_5 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 37 AS Expr1, SC09039 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_4 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 38 AS Expr1, SC09040 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_3 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 39 AS Expr1, SC09041 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_2 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 40 AS Expr1, SC09042 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_1 WITH (NOLOCK) ) AS View_1 ON "
                MySQLStr = MySQLStr & "SC010300.SC01135 = View_1.Expr1 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "tbl_WEB_Pictures ON SC010300.SC01001 = tbl_WEB_Pictures.ScalaItemCode LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "PL010300 ON SC010300.SC01058 = PL010300.PL01001 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "tbl_ItemCard0300 ON SC010300.SC01001 = tbl_ItemCard0300.SC01001 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "(SELECT SC03001, SC03003 AS WhQty, "
                MySQLStr = MySQLStr & "SC03003 - SC03004 - SC03005 AS WhAvl "
                MySQLStr = MySQLStr & "FROM SC030300 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC03002 = N'" & Declarations.WHNum & "')) AS t1 ON "
                MySQLStr = MySQLStr & "SC010300.SC01001 = t1.SC03001 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "(SELECT SC39001, SC39005 "
                MySQLStr = MySQLStr & "FROM SC390300 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC39002 = N'00')) AS t2 ON "
                MySQLStr = MySQLStr & "SC010300.SC01001 = t2.SC39001 "
                MySQLStr = MySQLStr & "WHERE (SC010300.SC01001 <> N'00000000') AND "
                MySQLStr = MySQLStr & "(tbl_ItemCard0300.IsBlocked = N'0') AND "
                MySQLStr = MySQLStr & "(Ltrim(Rtrim(SC010300.SC01066)) <> N'8')"
                If Trim(MyOrderLines.TextBox1.Text) = "" Then
                Else
                    MySQLStr = MySQLStr & "AND (SC010300.SC01058 = N'" & Trim(MyOrderLines.TextBox1.Text) & "') "
                End If
                If Trim(MyOrderLines.Button8.Text) = "Все прод." Then '---выводятся только доступные продукты
                    MySQLStr = MySQLStr & " AND (WhAvl > 0) "
                End If
                '---Условия поиска-----------
                MySQLStr = MySQLStr & "AND ((UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%') "
                MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%') "
                MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%') "
                MySQLStr = MySQLStr & "OR (UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%')) "
                MySQLStr = MySQLStr & "ORDER BY dbo.SC010300.SC01001  "
            Else
                '----В первое окно условие введено
                If Trim(MyOrderLines.TextBox3.Text) = "" Then
                    '----Во второе окно условие не введено
                    'MySQLStr = "SELECT tbl_WEB_Pictures.PictureSmall, SC010300.SC01001 AS ID, "
                    MySQLStr = "SELECT NULL, SC010300.SC01001 AS ID, "
                    MySQLStr = MySQLStr & "SC010300.SC01002 + ' ' + SC010300.SC01003 AS Name, "
                    MySQLStr = MySQLStr & "Round(ISNULL(t2.SC39005, 0) / " & Replace(CStr(Declarations.CurrencyValue), ",", ".") & ",2) AS Price, "
                    MySQLStr = MySQLStr & "SC010300.SC01060 AS SuppID, "
                    MySQLStr = MySQLStr & "View_1.txt AS UnitName, "
                    MySQLStr = MySQLStr & "SC010300.SC01042 AS TotalQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhQty, 0) AS WhQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhAvl, 0) AS WhAvl, "
                    MySQLStr = MySQLStr & "SC010300.SC01058 AS SuppCode, "
                    MySQLStr = MySQLStr & "ISNULL(PL010300.PL01002, N'') + ' ' + ISNULL(PL010300.PL01003, N'') AS SuppName, "
                    '---поставщик "неликвидов"
                    MySQLStr = MySQLStr & "CASE WHEN Ltrim(Rtrim(SC010300.SC01058)) = 'FIN001_U' THEN '+' ELSE '' END AS Dead, "
                    MySQLStr = MySQLStr & "LTRIM(RTRIM(tbl_ItemCard0300.ManufacturerItemCode)) AS ManufacturerItemCode "
                    MySQLStr = MySQLStr & "FROM SC010300 WITH (NOLOCK) INNER JOIN "
                    MySQLStr = MySQLStr & "(SELECT 0 AS Expr1, SC09002 AS txt "
                    MySQLStr = MySQLStr & "FROM SC090300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 1 AS Expr1, SC09003 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_40 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 2 AS Expr1, SC09004 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_39 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 3 AS Expr1, SC09005 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_38 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 4 AS Expr1, SC09006 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_37 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 5 AS Expr1, SC09007 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_36 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 6 AS Expr1, SC09008 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_35 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 7 AS Expr1, SC09009 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_34 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 8 AS Expr1, SC09010 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_33 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 9 AS Expr1, SC09011 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_32 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 10 AS Expr1, SC09012 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_31 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 11 AS Expr1, SC09013 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_30 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 12 AS Expr1, SC09014 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_29 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 13 AS Expr1, SC09015 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_28 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 14 AS Expr1, SC09016 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_27 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 15 AS Expr1, SC09017 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_26 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 16 AS Expr1, SC09018 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_25 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 17 AS Expr1, SC09019 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_24 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 18 AS Expr1, SC09020 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_23 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 19 AS Expr1, SC09021 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_22 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 20 AS Expr1, SC09022 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_21 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 21 AS Expr1, SC09023 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_20 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 22 AS Expr1, SC09024 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_19 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 23 AS Expr1, SC09025 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_18 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 24 AS Expr1, SC09026 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_17 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 25 AS Expr1, SC09027 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_16 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 26 AS Expr1, SC09028 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_15 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 27 AS Expr1, SC09029 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_14 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 28 AS Expr1, SC09030 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_13 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 29 AS Expr1, SC09031 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_12 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 30 AS Expr1, SC09032 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_11 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 31 AS Expr1, SC09033 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_10 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 32 AS Expr1, SC09034 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_9 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 33 AS Expr1, SC09035 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_8 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 34 AS Expr1, SC09036 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_7 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 35 AS Expr1, SC09037 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_6 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 36 AS Expr1, SC09038 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_5 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 37 AS Expr1, SC09039 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_4 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 38 AS Expr1, SC09040 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_3 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 39 AS Expr1, SC09041 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_2 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 40 AS Expr1, SC09042 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_1 WITH (NOLOCK) ) AS View_1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01135 = View_1.Expr1 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_WEB_Pictures ON SC010300.SC01001 = tbl_WEB_Pictures.ScalaItemCode LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "PL010300 ON SC010300.SC01058 = PL010300.PL01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_ItemCard0300 ON SC010300.SC01001 = tbl_ItemCard0300.SC01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC03001, SC03003 AS WhQty, "
                    MySQLStr = MySQLStr & "SC03003 - SC03004 - SC03005 AS WhAvl "
                    MySQLStr = MySQLStr & "FROM SC030300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC03002 = N'" & Declarations.WHNum & "')) AS t1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t1.SC03001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC39001, SC39005 "
                    MySQLStr = MySQLStr & "FROM SC390300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC39002 = N'00')) AS t2 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t2.SC39001 "
                    MySQLStr = MySQLStr & "WHERE (SC010300.SC01001 <> N'00000000') AND "
                    MySQLStr = MySQLStr & "(tbl_ItemCard0300.IsBlocked = N'0') AND "
                    MySQLStr = MySQLStr & "(Ltrim(Rtrim(SC010300.SC01066)) <> N'8')"
                    If Trim(MyOrderLines.TextBox1.Text) = "" Then
                    Else
                        MySQLStr = MySQLStr & "AND (SC010300.SC01058 = N'" & Trim(MyOrderLines.TextBox1.Text) & "') "
                    End If
                    If Trim(MyOrderLines.Button8.Text) = "Все прод." Then '---выводятся только доступные продукты
                        MySQLStr = MySQLStr & " AND (WhAvl > 0) "
                    End If
                    '---Условия поиска-----------
                    MySQLStr = MySQLStr & "AND ((UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "OR (UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%')) "
                    MySQLStr = MySQLStr & "ORDER BY dbo.SC010300.SC01001  "
                Else
                    '----Условия введены в оба окна
                    'MySQLStr = "SELECT tbl_WEB_Pictures.PictureSmall, SC010300.SC01001 AS ID, "
                    MySQLStr = "SELECT NULL, SC010300.SC01001 AS ID, "
                    MySQLStr = MySQLStr & "SC010300.SC01002 + ' ' + SC010300.SC01003 AS Name, "
                    MySQLStr = MySQLStr & "Round(ISNULL(t2.SC39005, 0) / " & Replace(CStr(Declarations.CurrencyValue), ",", ".") & ",2) AS Price, "
                    MySQLStr = MySQLStr & "SC010300.SC01060 AS SuppID, "
                    MySQLStr = MySQLStr & "View_1.txt AS UnitName, "
                    MySQLStr = MySQLStr & "SC010300.SC01042 AS TotalQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhQty, 0) AS WhQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhAvl, 0) AS WhAvl, "
                    MySQLStr = MySQLStr & "SC010300.SC01058 AS SuppCode, "
                    MySQLStr = MySQLStr & "ISNULL(PL010300.PL01002, N'') + ' ' + ISNULL(PL010300.PL01003, N'') AS SuppName, "
                    '---поставщик "неликвидов"
                    MySQLStr = MySQLStr & "CASE WHEN Ltrim(Rtrim(SC010300.SC01058)) = 'FIN001_U' THEN '+' ELSE '' END AS Dead, "
                    MySQLStr = MySQLStr & "LTRIM(RTRIM(tbl_ItemCard0300.ManufacturerItemCode)) AS ManufacturerItemCode "
                    MySQLStr = MySQLStr & "FROM SC010300 WITH (NOLOCK) INNER JOIN "
                    MySQLStr = MySQLStr & "(SELECT 0 AS Expr1, SC09002 AS txt "
                    MySQLStr = MySQLStr & "FROM SC090300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 1 AS Expr1, SC09003 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_40 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 2 AS Expr1, SC09004 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_39 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 3 AS Expr1, SC09005 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_38 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 4 AS Expr1, SC09006 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_37 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 5 AS Expr1, SC09007 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_36 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 6 AS Expr1, SC09008 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_35 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 7 AS Expr1, SC09009 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_34 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 8 AS Expr1, SC09010 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_33 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 9 AS Expr1, SC09011 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_32 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 10 AS Expr1, SC09012 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_31 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 11 AS Expr1, SC09013 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_30 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 12 AS Expr1, SC09014 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_29 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 13 AS Expr1, SC09015 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_28 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 14 AS Expr1, SC09016 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_27 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 15 AS Expr1, SC09017 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_26 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 16 AS Expr1, SC09018 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_25 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 17 AS Expr1, SC09019 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_24 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 18 AS Expr1, SC09020 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_23 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 19 AS Expr1, SC09021 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_22 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 20 AS Expr1, SC09022 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_21 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 21 AS Expr1, SC09023 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_20 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 22 AS Expr1, SC09024 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_19 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 23 AS Expr1, SC09025 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_18 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 24 AS Expr1, SC09026 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_17 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 25 AS Expr1, SC09027 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_16 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 26 AS Expr1, SC09028 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_15 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 27 AS Expr1, SC09029 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_14 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 28 AS Expr1, SC09030 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_13 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 29 AS Expr1, SC09031 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_12 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 30 AS Expr1, SC09032 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_11 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 31 AS Expr1, SC09033 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_10 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 32 AS Expr1, SC09034 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_9 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 33 AS Expr1, SC09035 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_8 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 34 AS Expr1, SC09036 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_7 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 35 AS Expr1, SC09037 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_6 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 36 AS Expr1, SC09038 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_5 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 37 AS Expr1, SC09039 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_4 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 38 AS Expr1, SC09040 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_3 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 39 AS Expr1, SC09041 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_2 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 40 AS Expr1, SC09042 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_1 WITH (NOLOCK) ) AS View_1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01135 = View_1.Expr1 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_WEB_Pictures ON SC010300.SC01001 = tbl_WEB_Pictures.ScalaItemCode LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "PL010300 ON SC010300.SC01058 = PL010300.PL01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_ItemCard0300 ON SC010300.SC01001 = tbl_ItemCard0300.SC01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC03001, SC03003 AS WhQty, "
                    MySQLStr = MySQLStr & "SC03003 - SC03004 - SC03005 AS WhAvl "
                    MySQLStr = MySQLStr & "FROM SC030300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC03002 = N'" & Declarations.WHNum & "')) AS t1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t1.SC03001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC39001, SC39005 "
                    MySQLStr = MySQLStr & "FROM SC390300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC39002 = N'00')) AS t2 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t2.SC39001 "
                    MySQLStr = MySQLStr & "WHERE (SC010300.SC01001 <> N'00000000') AND "
                    MySQLStr = MySQLStr & "(tbl_ItemCard0300.IsBlocked = N'0') AND "
                    MySQLStr = MySQLStr & "(Ltrim(Rtrim(SC010300.SC01066)) <> N'8')"
                    If Trim(MyOrderLines.TextBox1.Text) = "" Then
                    Else
                        MySQLStr = MySQLStr & "AND (SC010300.SC01058 = N'" & Trim(MyOrderLines.TextBox1.Text) & "') "
                    End If
                    If Trim(MyOrderLines.Button8.Text) = "Все прод." Then '---выводятся только доступные продукты
                        MySQLStr = MySQLStr & " AND (WhAvl > 0) "
                    End If
                    '---Условия поиска-----------
                    MySQLStr = MySQLStr & "AND (((UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%')) "
                    MySQLStr = MySQLStr & "OR ((UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%')) "
                    MySQLStr = MySQLStr & "OR ((UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%')) "
                    MySQLStr = MySQLStr & "OR ((UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyOrderLines.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyOrderLines.TextBox3.Text) & "%'))) "
                    MySQLStr = MySQLStr & "ORDER BY dbo.SC010300.SC01001  "
                End If
            End If
        ElseIf MyItemSelectList.MySrcWin = "ItemSelect" Then
            If Trim(MyItemSelect.TextBox2.Text) = "" Then
                '----В первое окно условие не введено - считаем, что во второе введено
                'MySQLStr = "SELECT tbl_WEB_Pictures.PictureSmall, SC010300.SC01001 AS ID, "
                MySQLStr = "SELECT NULL, SC010300.SC01001 AS ID, "
                MySQLStr = MySQLStr & "SC010300.SC01002 + ' ' + SC010300.SC01003 AS Name, "
                MySQLStr = MySQLStr & "Round(ISNULL(t2.SC39005, 0) / " & Replace(CStr(Declarations.CurrencyValue), ",", ".") & ",2) AS Price, "
                MySQLStr = MySQLStr & "SC010300.SC01060 AS SuppID, "
                MySQLStr = MySQLStr & "View_1.txt AS UnitName, "
                MySQLStr = MySQLStr & "SC010300.SC01042 AS TotalQty, "
                MySQLStr = MySQLStr & "ISNULL(t1.WhQty, 0) AS WhQty, "
                MySQLStr = MySQLStr & "ISNULL(t1.WhAvl, 0) AS WhAvl, "
                MySQLStr = MySQLStr & "SC010300.SC01058 AS SuppCode, "
                MySQLStr = MySQLStr & "ISNULL(PL010300.PL01002, N'') + ' ' + ISNULL(PL010300.PL01003, N'') AS SuppName, "
                '---поставщик "неликвидов"
                MySQLStr = MySQLStr & "CASE WHEN Ltrim(Rtrim(SC010300.SC01058)) = 'FIN001_U' THEN '+' ELSE '' END AS Dead, "
                MySQLStr = MySQLStr & "LTRIM(RTRIM(tbl_ItemCard0300.ManufacturerItemCode)) AS ManufacturerItemCode "
                MySQLStr = MySQLStr & "FROM SC010300 WITH (NOLOCK) INNER JOIN "
                MySQLStr = MySQLStr & "(SELECT 0 AS Expr1, SC09002 AS txt "
                MySQLStr = MySQLStr & "FROM SC090300 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 1 AS Expr1, SC09003 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_40 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 2 AS Expr1, SC09004 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_39 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 3 AS Expr1, SC09005 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_38 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 4 AS Expr1, SC09006 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_37 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 5 AS Expr1, SC09007 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_36 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 6 AS Expr1, SC09008 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_35 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 7 AS Expr1, SC09009 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_34 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 8 AS Expr1, SC09010 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_33 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 9 AS Expr1, SC09011 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_32 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 10 AS Expr1, SC09012 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_31 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 11 AS Expr1, SC09013 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_30 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 12 AS Expr1, SC09014 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_29 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 13 AS Expr1, SC09015 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_28 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 14 AS Expr1, SC09016 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_27 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 15 AS Expr1, SC09017 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_26 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 16 AS Expr1, SC09018 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_25 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 17 AS Expr1, SC09019 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_24 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 18 AS Expr1, SC09020 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_23 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 19 AS Expr1, SC09021 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_22 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 20 AS Expr1, SC09022 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_21 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 21 AS Expr1, SC09023 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_20 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 22 AS Expr1, SC09024 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_19 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 23 AS Expr1, SC09025 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_18 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 24 AS Expr1, SC09026 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_17 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 25 AS Expr1, SC09027 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_16 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 26 AS Expr1, SC09028 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_15 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 27 AS Expr1, SC09029 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_14 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 28 AS Expr1, SC09030 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_13 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 29 AS Expr1, SC09031 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_12 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 30 AS Expr1, SC09032 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_11 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 31 AS Expr1, SC09033 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_10 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 32 AS Expr1, SC09034 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_9 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 33 AS Expr1, SC09035 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_8 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 34 AS Expr1, SC09036 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_7 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 35 AS Expr1, SC09037 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_6 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 36 AS Expr1, SC09038 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_5 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 37 AS Expr1, SC09039 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_4 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 38 AS Expr1, SC09040 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_3 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 39 AS Expr1, SC09041 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_2 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                MySQLStr = MySQLStr & "UNION "
                MySQLStr = MySQLStr & "SELECT 40 AS Expr1, SC09042 "
                MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_1 WITH (NOLOCK) ) AS View_1 ON "
                MySQLStr = MySQLStr & "SC010300.SC01135 = View_1.Expr1 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "tbl_WEB_Pictures ON SC010300.SC01001 = tbl_WEB_Pictures.ScalaItemCode LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "PL010300 ON SC010300.SC01058 = PL010300.PL01001 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "tbl_ItemCard0300 ON SC010300.SC01001 = tbl_ItemCard0300.SC01001 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "(SELECT SC03001, SC03003 AS WhQty, "
                MySQLStr = MySQLStr & "SC03003 - SC03004 - SC03005 AS WhAvl "
                MySQLStr = MySQLStr & "FROM SC030300 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC03002 = N'" & Declarations.WHNum & "')) AS t1 ON "
                MySQLStr = MySQLStr & "SC010300.SC01001 = t1.SC03001 LEFT OUTER JOIN "
                MySQLStr = MySQLStr & "(SELECT SC39001, SC39005 "
                MySQLStr = MySQLStr & "FROM SC390300 WITH (NOLOCK) "
                MySQLStr = MySQLStr & "WHERE (SC39002 = N'00')) AS t2 ON "
                MySQLStr = MySQLStr & "SC010300.SC01001 = t2.SC39001 "
                MySQLStr = MySQLStr & "WHERE (SC010300.SC01001 <> N'00000000') AND "
                MySQLStr = MySQLStr & "(tbl_ItemCard0300.IsBlocked = N'0') AND "
                MySQLStr = MySQLStr & "(Ltrim(Rtrim(SC010300.SC01066)) <> N'8')"
                If Trim(MyItemSelect.TextBox1.Text) = "" Then
                Else
                    MySQLStr = MySQLStr & "AND (SC010300.SC01058 = N'" & Trim(MyItemSelect.TextBox1.Text) & "') "
                End If
                '---Условия поиска-----------
                MySQLStr = MySQLStr & "AND ((UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%') "
                MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%') "
                MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%') "
                MySQLStr = MySQLStr & "OR (UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%')) "
                MySQLStr = MySQLStr & "ORDER BY dbo.SC010300.SC01001  "
            Else
                '----В первое окно условие введено
                If Trim(MyItemSelect.TextBox3.Text) = "" Then
                    '----Во второе окно условие не введено
                    'MySQLStr = "SELECT tbl_WEB_Pictures.PictureSmall, SC010300.SC01001 AS ID, "
                    MySQLStr = "SELECT NULL, SC010300.SC01001 AS ID, "
                    MySQLStr = MySQLStr & "SC010300.SC01002 + ' ' + SC010300.SC01003 AS Name, "
                    MySQLStr = MySQLStr & "Round(ISNULL(t2.SC39005, 0) / " & Replace(CStr(Declarations.CurrencyValue), ",", ".") & ",2) AS Price, "
                    MySQLStr = MySQLStr & "SC010300.SC01060 AS SuppID, "
                    MySQLStr = MySQLStr & "View_1.txt AS UnitName, "
                    MySQLStr = MySQLStr & "SC010300.SC01042 AS TotalQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhQty, 0) AS WhQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhAvl, 0) AS WhAvl, "
                    MySQLStr = MySQLStr & "SC010300.SC01058 AS SuppCode, "
                    MySQLStr = MySQLStr & "ISNULL(PL010300.PL01002, N'') + ' ' + ISNULL(PL010300.PL01003, N'') AS SuppName, "
                    '---поставщик "неликвидов"
                    MySQLStr = MySQLStr & "CASE WHEN Ltrim(Rtrim(SC010300.SC01058)) = 'FIN001_U' THEN '+' ELSE '' END AS Dead, "
                    MySQLStr = MySQLStr & "LTRIM(RTRIM(tbl_ItemCard0300.ManufacturerItemCode)) AS ManufacturerItemCode "
                    MySQLStr = MySQLStr & "FROM SC010300 WITH (NOLOCK) INNER JOIN "
                    MySQLStr = MySQLStr & "(SELECT 0 AS Expr1, SC09002 AS txt "
                    MySQLStr = MySQLStr & "FROM SC090300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 1 AS Expr1, SC09003 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_40 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 2 AS Expr1, SC09004 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_39 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 3 AS Expr1, SC09005 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_38 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 4 AS Expr1, SC09006 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_37 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 5 AS Expr1, SC09007 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_36 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 6 AS Expr1, SC09008 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_35 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 7 AS Expr1, SC09009 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_34 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 8 AS Expr1, SC09010 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_33 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 9 AS Expr1, SC09011 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_32 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 10 AS Expr1, SC09012 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_31 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 11 AS Expr1, SC09013 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_30 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 12 AS Expr1, SC09014 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_29 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 13 AS Expr1, SC09015 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_28 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 14 AS Expr1, SC09016 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_27 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 15 AS Expr1, SC09017 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_26 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 16 AS Expr1, SC09018 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_25 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 17 AS Expr1, SC09019 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_24 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 18 AS Expr1, SC09020 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_23 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 19 AS Expr1, SC09021 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_22 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 20 AS Expr1, SC09022 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_21 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 21 AS Expr1, SC09023 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_20 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 22 AS Expr1, SC09024 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_19 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 23 AS Expr1, SC09025 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_18 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 24 AS Expr1, SC09026 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_17 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 25 AS Expr1, SC09027 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_16 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 26 AS Expr1, SC09028 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_15 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 27 AS Expr1, SC09029 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_14 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 28 AS Expr1, SC09030 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_13 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 29 AS Expr1, SC09031 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_12 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 30 AS Expr1, SC09032 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_11 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 31 AS Expr1, SC09033 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_10 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 32 AS Expr1, SC09034 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_9 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 33 AS Expr1, SC09035 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_8 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 34 AS Expr1, SC09036 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_7 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 35 AS Expr1, SC09037 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_6 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 36 AS Expr1, SC09038 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_5 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 37 AS Expr1, SC09039 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_4 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 38 AS Expr1, SC09040 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_3 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 39 AS Expr1, SC09041 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_2 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 40 AS Expr1, SC09042 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_1 WITH (NOLOCK) ) AS View_1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01135 = View_1.Expr1 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_WEB_Pictures ON SC010300.SC01001 = tbl_WEB_Pictures.ScalaItemCode LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "PL010300 ON SC010300.SC01058 = PL010300.PL01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_ItemCard0300 ON SC010300.SC01001 = tbl_ItemCard0300.SC01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC03001, SC03003 AS WhQty, "
                    MySQLStr = MySQLStr & "SC03003 - SC03004 - SC03005 AS WhAvl "
                    MySQLStr = MySQLStr & "FROM SC030300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC03002 = N'" & Declarations.WHNum & "')) AS t1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t1.SC03001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC39001, SC39005 "
                    MySQLStr = MySQLStr & "FROM SC390300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC39002 = N'00')) AS t2 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t2.SC39001 "
                    MySQLStr = MySQLStr & "WHERE (SC010300.SC01001 <> N'00000000') AND "
                    MySQLStr = MySQLStr & "(tbl_ItemCard0300.IsBlocked = N'0') AND "
                    MySQLStr = MySQLStr & "(Ltrim(Rtrim(SC010300.SC01066)) <> N'8')"
                    If Trim(MyItemSelect.TextBox1.Text) = "" Then
                    Else
                        MySQLStr = MySQLStr & "AND (SC010300.SC01058 = N'" & Trim(MyItemSelect.TextBox1.Text) & "') "
                    End If
                    '---Условия поиска-----------
                    MySQLStr = MySQLStr & "AND ((UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "OR (UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "OR (UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%')) "
                    MySQLStr = MySQLStr & "ORDER BY dbo.SC010300.SC01001  "
                Else
                    '----Условия введены в оба окна
                    'MySQLStr = "SELECT tbl_WEB_Pictures.PictureSmall, SC010300.SC01001 AS ID, "
                    MySQLStr = "SELECT NULL, SC010300.SC01001 AS ID, "
                    MySQLStr = MySQLStr & "SC010300.SC01002 + ' ' + SC010300.SC01003 AS Name, "
                    MySQLStr = MySQLStr & "Round(ISNULL(t2.SC39005, 0) / " & Replace(CStr(Declarations.CurrencyValue), ",", ".") & ",2) AS Price, "
                    MySQLStr = MySQLStr & "SC010300.SC01060 AS SuppID, "
                    MySQLStr = MySQLStr & "View_1.txt AS UnitName, "
                    MySQLStr = MySQLStr & "SC010300.SC01042 AS TotalQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhQty, 0) AS WhQty, "
                    MySQLStr = MySQLStr & "ISNULL(t1.WhAvl, 0) AS WhAvl, "
                    MySQLStr = MySQLStr & "SC010300.SC01058 AS SuppCode, "
                    MySQLStr = MySQLStr & "ISNULL(PL010300.PL01002, N'') + ' ' + ISNULL(PL010300.PL01003, N'') AS SuppName, "
                    '---поставщик "неликвидов"
                    MySQLStr = MySQLStr & "CASE WHEN Ltrim(Rtrim(SC010300.SC01058)) = 'FIN001_U' THEN '+' ELSE '' END AS Dead, "
                    MySQLStr = MySQLStr & "LTRIM(RTRIM(tbl_ItemCard0300.ManufacturerItemCode)) AS ManufacturerItemCode "
                    MySQLStr = MySQLStr & "FROM SC010300 WITH (NOLOCK) INNER JOIN "
                    MySQLStr = MySQLStr & "(SELECT 0 AS Expr1, SC09002 AS txt "
                    MySQLStr = MySQLStr & "FROM SC090300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 1 AS Expr1, SC09003 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_40 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 2 AS Expr1, SC09004 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_39 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 3 AS Expr1, SC09005 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_38 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 4 AS Expr1, SC09006 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_37 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 5 AS Expr1, SC09007 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_36 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 6 AS Expr1, SC09008 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_35 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 7 AS Expr1, SC09009 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_34 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 8 AS Expr1, SC09010 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_33 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 9 AS Expr1, SC09011 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_32 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 10 AS Expr1, SC09012 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_31 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 11 AS Expr1, SC09013 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_30 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 12 AS Expr1, SC09014 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_29 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 13 AS Expr1, SC09015 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_28 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 14 AS Expr1, SC09016 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_27 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 15 AS Expr1, SC09017 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_26 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 16 AS Expr1, SC09018 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_25 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 17 AS Expr1, SC09019 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_24 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 18 AS Expr1, SC09020 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_23 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 19 AS Expr1, SC09021 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_22 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 20 AS Expr1, SC09022 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_21 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 21 AS Expr1, SC09023 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_20 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 22 AS Expr1, SC09024 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_19 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 23 AS Expr1, SC09025 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_18 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 24 AS Expr1, SC09026 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_17 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 25 AS Expr1, SC09027 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_16 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 26 AS Expr1, SC09028 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_15 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 27 AS Expr1, SC09029 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_14 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 28 AS Expr1, SC09030 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_13 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 29 AS Expr1, SC09031 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_12 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 30 AS Expr1, SC09032 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_11 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 31 AS Expr1, SC09033 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_10 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 32 AS Expr1, SC09034 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_9 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 33 AS Expr1, SC09035 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_8 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 34 AS Expr1, SC09036 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_7 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 35 AS Expr1, SC09037 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_6 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 36 AS Expr1, SC09038 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_5 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 37 AS Expr1, SC09039 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_4 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 38 AS Expr1, SC09040 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_3 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 39 AS Expr1, SC09041 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_2 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC09001 = 'RUS') "
                    MySQLStr = MySQLStr & "UNION "
                    MySQLStr = MySQLStr & "SELECT 40 AS Expr1, SC09042 "
                    MySQLStr = MySQLStr & "FROM SC090300 AS SC090300_1 WITH (NOLOCK) ) AS View_1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01135 = View_1.Expr1 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_WEB_Pictures ON SC010300.SC01001 = tbl_WEB_Pictures.ScalaItemCode LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "PL010300 ON SC010300.SC01058 = PL010300.PL01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "tbl_ItemCard0300 ON SC010300.SC01001 = tbl_ItemCard0300.SC01001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC03001, SC03003 AS WhQty, "
                    MySQLStr = MySQLStr & "SC03003 - SC03004 - SC03005 AS WhAvl "
                    MySQLStr = MySQLStr & "FROM SC030300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC03002 = N'" & Declarations.WHNum & "')) AS t1 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t1.SC03001 LEFT OUTER JOIN "
                    MySQLStr = MySQLStr & "(SELECT SC39001, SC39005 "
                    MySQLStr = MySQLStr & "FROM SC390300 WITH (NOLOCK) "
                    MySQLStr = MySQLStr & "WHERE (SC39002 = N'00')) AS t2 ON "
                    MySQLStr = MySQLStr & "SC010300.SC01001 = t2.SC39001 "
                    MySQLStr = MySQLStr & "WHERE (SC010300.SC01001 <> N'00000000') AND "
                    MySQLStr = MySQLStr & "(tbl_ItemCard0300.IsBlocked = N'0') AND "
                    MySQLStr = MySQLStr & "(Ltrim(Rtrim(SC010300.SC01066)) <> N'8')"
                    If Trim(MyItemSelect.TextBox1.Text) = "" Then
                    Else
                        MySQLStr = MySQLStr & "AND (SC010300.SC01058 = N'" & Trim(MyItemSelect.TextBox1.Text) & "') "
                    End If
                    '---Условия поиска-----------
                    MySQLStr = MySQLStr & "AND (((UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(SC010300.SC01001) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%')) "
                    MySQLStr = MySQLStr & "OR ((UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(SC010300.SC01002 + ' ' + SC010300.SC01003) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%')) "
                    MySQLStr = MySQLStr & "OR ((UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(SC010300.SC01060) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%')) "
                    MySQLStr = MySQLStr & "OR ((UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyItemSelect.TextBox2.Text) & "%') "
                    MySQLStr = MySQLStr & "AND (UPPER(tbl_ItemCard0300.ManufacturerItemCode) LIKE N'%" & UCase(MyItemSelect.TextBox3.Text) & "%'))) "
                    MySQLStr = MySQLStr & "ORDER BY dbo.SC010300.SC01001  "
                End If
            End If
        End If

        DataGridView1.RowTemplate.MinimumHeight = 35

        Try
            MyAdapter = New SqlClient.SqlDataAdapter(MySQLStr, Declarations.MyNETConnStr)
            MyAdapter.SelectCommand.CommandTimeout = 600
            MyAdapter.Fill(MyDs)
            DataGridView1.DataSource = MyDs.Tables(0)
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try

        DataGridView1.Columns(0).HeaderText = "Кар тин ка"
        DataGridView1.Columns(0).Width = 35
        DataGridView1.Columns(0).Visible = False
        DataGridView1.Columns(1).HeaderText = "ID продукта"
        DataGridView1.Columns(1).Width = 110
        DataGridView1.Columns(2).HeaderText = "Имя продукта"
        DataGridView1.Columns(2).Width = 300
        DataGridView1.Columns(3).HeaderText = "Прайс"
        DataGridView1.Columns(3).Width = 80
        DataGridView1.Columns(4).HeaderText = "Код тов постав"
        DataGridView1.Columns(4).Width = 110
        DataGridView1.Columns(5).HeaderText = "Ед изм"
        DataGridView1.Columns(5).Width = 40
        DataGridView1.Columns(6).HeaderText = "Всего на складах"
        DataGridView1.Columns(6).Width = 115
        DataGridView1.Columns(7).HeaderText = "Ост" + " " + Declarations.WHNum
        DataGridView1.Columns(7).Width = 115
        DataGridView1.Columns(8).HeaderText = "Дост" + " " + Declarations.WHNum
        DataGridView1.Columns(8).Width = 115
        DataGridView1.Columns(9).HeaderText = "Поставщик ID"
        DataGridView1.Columns(9).Width = 70
        DataGridView1.Columns(10).HeaderText = "Поставщик"
        DataGridView1.Columns(10).Width = 200
        DataGridView1.Columns(11).HeaderText = "Неликвид"
        DataGridView1.Columns(11).Width = 70
        DataGridView1.Columns(12).HeaderText = "Код тов произв"
        DataGridView1.Columns(12).Width = 150

        If DataGridView1.Rows.Count > 0 Then
            Button1.Enabled = True
            Button4.Enabled = True
        Else
            Button1.Enabled = False
            Button4.Enabled = False
        End If
    End Sub

    Private Sub DataGridView1_CellFormatting(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellFormattingEventArgs) Handles DataGridView1.CellFormatting
        '////////////////////////////////////////////////////////////////////////////////////////
        '//
        '// смена выделения неликвидов
        '//
        '////////////////////////////////////////////////////////////////////////////////////////
        Dim row As DataGridViewRow

        row = DataGridView1.Rows(e.RowIndex)
        If row.Cells(11).Value.ToString = "+" Then
            row.DefaultCellStyle.Font = New Font(row.InheritedStyle.Font, FontStyle.Bold)
            row.DefaultCellStyle.ForeColor = Color.Red
        End If
    End Sub

    Private Sub DataGridView1_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles DataGridView1.DoubleClick
        '/////////////////////////////////////////////////////////////////////////////////////
        '//
        '// Выход с выбором запаса
        '// 
        '/////////////////////////////////////////////////////////////////////////////////////

        ItemSelect()
    End Sub
End Class